### ISSUE TITLE
rusty_sr.exe <INPUT_FILE> <OUTPUT_FILE>  but why the result is very poor

### ISSUE THREAD

**Issue by c1a1o1** [millardjn/rusty_sr#1]
rusty_sr.exe <INPUT_FILE> <OUTPUT_FILE>  but why the result is very poor
Do you have a better way ??

**Comment by millardjn** [comment]
Hi
Did the program produce an error message, or is the output image quality not good?

One known type of image which the networks aren't trained to handle is computer generated images with aliasing/jaggies. I've been looking at training settings to handle this case.

If you are experiencing this, or have discovered a new failure mode i would be very interested to know.

Cheers

**Comment by millardjn** [comment]
Discussion continued in https://github.com/millardjn/rusty_sr/issues/4
