### ISSUE TITLE
Could you share the parameters used for the README images?

### ISSUE THREAD

**Issue by anowell** [millardjn/rusty_sr#2]
I haven't figured out how to get comparable results for the images on the README. If I run butterfly_nn.png with the imagenet parameters, I get a high-res (2304x1539) image that basically looks like a stretched image:

![before-and-after](https://cloud.githubusercontent.com/assets/2629687/22840773/0a447e10-ef8c-11e6-9130-5a29168fbd78.png)

I've tried a few combinations of parameters with the different images from your README and seem to minor variations on the same results. I feel like I'm overlooking something. Any insights?

**Comment by millardjn** [comment]
Hi! The <image>_nn files are nearest neighbour upscalings of the low resolution files which exist just for ease of formatting the readme. You can downscale those or the original set14 images by a factor of 3 to get the low resolution image back.
Other than that, all images are default settings, except the cartoon on which the -p anime setting was used.

Downscaling for testing should be done with the -d flag or a program that supports linear RGB downscaling, for best results. Downscaling the <image>_rs files isn't a good idea as the neural networks aren't perfectly idempotent.

**Comment by millardjn** [comment]
It seems reproducing the README examples is a common desire so I've committed the low resolution versions of the example images: https://github.com/millardjn/rusty_sr/issues/4.

**Comment by millardjn** [comment]
I hope the Algorithmia API goes well, feel free to contact me if you want any help with this, Alumina, or performance tweaking matrixmultiply_mt.
Closing this for now.

**Comment by anowell** [comment]
The Algorithmia API implementation went well - it only took about an hour to port (you should recognize most of [this code](https://algorithmia.com/algorithms/anowell/enhance_resolution/edit)). Unfortunately, I uncovered a platform bug that is blocking me from publishing it as an API, but the fix is queued up for Monday. So stay tuned. :-)

And if you have any interest in owning/maintaining it on Algorithmia, just let me know. I'd be happy to hand it over. :-)

**Comment by anowell** [comment]
(oh. and yeah, your clarifications about the README images were exactly what I needed to know. 👍

**Comment by millardjn** [comment]
Thanks, that would be awesome! I've also got some blind deconvolution work which I think would be a good fit for the platform. I'll have a look around the dev api.
