### ISSUE TITLE
Do you have some ways  to make cartoon_nn.png  to   cartoon_nr.png??

### ISSUE THREAD

**Issue by c1a1o1** [millardjn/rusty_sr#6]
Do you have some ways  to make cartoon_nn.png  to   cartoon_nr.png??
I  think  you  can !
Thank you !

**Comment by millardjn** [comment]
Do you mean cartoon_lr.png?
To downsample an image try: `rusty_sr.exe -d cartoon_nn.png cartoon_lr.png`

**Comment by c1a1o1** [comment]
In other words! I want to  make  a poor picture  to a good quality??
May be like  RAISR

**Comment by millardjn** [comment]
Rusty_SR takes small images and makes them bigger while trying for the best quality.
It isn't trained to take images with scaling artifacts/visible pixilation already included and remove them.
If you can get a hold of the original low resolution image (or cleanly downsample the poorly upsampled image in another program) you can then try upscaling it with this.
